apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: skn1942/grafana:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9090


---
apiVersion: v1
kind: Service
metadata:
  name: grafana-srv
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      protocol: TCP
      port: 9090
      targetPort: 9090
