# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

scrape_configs:
  - job_name: "Sum"
    scrape_interval: 5s
    static_configs:
      - targets:
          - ${SUM_SERVICE_URL}

  - job_name: "Subtract"
    scrape_interval: 5s
    static_configs:
      - targets:
          - ${SUBTRACT_SERVICE_URL}

  - job_name: "Multiply"
    scrape_interval: 5s
    static_configs:
      - targets:
          - ${MULTIPLY_SERVICE_URL}

  - job_name: "Division"
    scrape_interval: 5s
    static_configs:
      - targets:
          - ${DIVISION_SERVICE_URL}

  - job_name: "Power"
    scrape_interval: 5s
    static_configs:
      - targets:
          - ${POWER_SERVICE_URL}

  - job_name: "Sqrt"
    scrape_interval: 5s
    static_configs:
      - targets:
          - ${SQRT_SERVICE_URL}

  - job_name: "Orchestrator"
    scrape_interval: 5s
    static_configs:
      - targets:
          - ${ORCHESTRATOR_SERVICE_URL}
