name: tests-division

on: 
  pull_request:
    paths:
      - 'division/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - run : cd division && pip install -r requirements.txt && pytest
