name: tests-sum

on: 
  pull_request:
    paths:
      - 'sum/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - run : cd sum && pip install -r requirements.txt && pytest
